name: Build and deploy Node.js app to Azure Web App - portalteste

on:
  push:
    branches:
      - migration-to-next
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # <— Use Node LTS compatível com Next.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Zip artifact
        run: zip -r release.zip .next node_modules public package.json next.config.js

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_… }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_… }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_… }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'portalteste'
          slot-name: 'production'
          package: 'release.zip'
          enable-oryx-build: false
