name: Build and deploy Node.js app to Azure Web App - portalteste

on:
  push:
    branches:
      - migration-to-next
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: portalteste
  AZURE_RESOURCE_GROUP: seu-resource-group
  PACKAGE_PATH: release.zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: node-version: '18.x'
      - name: Install & build
        run: |
          npm ci
          npm run build
      - name: Zip build artifacts
        run: |
          zip -r $PACKAGE_PATH .next node_modules public package.json next.config.js
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: $PACKAGE_PATH

    deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure App Settings
        run: |
          az webapp config appsettings set \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name        $AZURE_WEBAPP_NAME \
            --settings    \
              WEBSITE_RUN_FROM_PACKAGE=1 \
              WEBSITE_NODE_DEFAULT_VERSION=~18 \
              SCM_DO_BUILD_DURING_DEPLOYMENT=false

      - name: Configure Startup Command
        run: |
          az webapp config set \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name         $AZURE_WEBAPP_NAME \
            --startup-file "npm start -- -p \$PORT"

      - name: Deploy via Zip-Deploy CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deployment source config-zip \
              --resource-group $AZURE_RESOURCE_GROUP \
              --name          $AZURE_WEBAPP_NAME \
              --src           $PACKAGE_PATH \
              --clean         true

