name: Build and deploy Node.js app to Azure Web App - portateste

permissions:
  id-token: write      # necessário para Azure OIDC login
  contents: read       # necessário para checkout e download-artifact
on:
  push:
    branches:
      - migration-to-next
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build Next.js
        run: npm run build

      - name: Prune devDependencies
        run: npm prune --production

      - name: Package release.zip
        run: |
          zip -r release.zip \
            .next \
            node_modules \
            public \
            package.json \
            next.config.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ADF2A75C1AFD42C1AD5E7A1D5781D51E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_415BB9ADB58B42EFBB536A9E4CCCC173 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1D18051F58784C2D916B2C23570E00A9 }}

      - name: Configure Run-From-Package
        uses: azure/CLI@v1
        with:
          azcliversion: '2.33.0'
          inlineScript: |
            az webapp config appsettings set \
              --resource-group rg-teste-webapp \
              --name portateste \
              --settings WEBSITE_RUN_FROM_PACKAGE=1 SCM_DO_BUILD_DURING_DEPLOYMENT=false

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'portateste'
          slot-name: 'Production'
          package: release.zip
